language: php

matrix:
  include:
    - php: 7.4
      dist: bionic
    - php: 8.1
      dist: jammy

install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phpunit
  - vendor/bin/phpunit test/CommonMarkTestWeak.php || true
  - '[ -z "$TRAVIS_TAG" ] || [ "$TRAVIS_TAG" == "$(php -r "require(\"Parsedown.php\"); echo Parsedown::version;")" ]'
